import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    signInText: 'SIGN IN',
    justo: 'Justo',
    notificationHeader: 'Notification',
    dashboardHeader: 'Dashboard',
    registrationHeader: 'Registration',
    propertyHeader: 'Property',
    propertyManagementHeader: 'Property Management',
    agencyHeader: 'Agency (CP)',
    leadManagementHeader: 'Lead Management',
    appointmentWithCPHeader: 'Appointment With CP',
    appointmentForVisitHeader: 'Appointment For Site Visit',
    reportHeader: 'Report',
    chatHeader: 'Chat',
    supportHeader: 'Support',
    settingHeader: 'Setting',
    logout: 'LogOut',
    versionText: 'version',
    forgotPassword: 'Forgot Password?',
    newUserText: 'New User?',
    signUp: 'Sign Up',
    byCreating: 'By Signing up you agree to our',
    termsAndCondition: 'Terms & Conditions',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    ofJusto: 'of Justo.',
    basicInfoText: 'Basic Information',
    active: 'Active',
    view: 'View',
    unsubscribe: 'Unsubscribe',
    subscribe: 'Subscribe',
    propertyDetailHeader: 'Property Detail',
    confirmation: 'Confirmation',
    ConfirmationModalTxt: 'Select the reason for\r\nunsubscribe this property.',
    Confirm: 'CONFIRM',
    searchProperty: 'Search Property',
    apply: 'APPLY',
    resend: 'Resend',
    notRecived: `Didn't receive the code?`,
    codeSent: 'A verification code has been sent to',
    your: ' your',
    email: 'email address',
    otpVerification: 'OTP VERIFICATION'
  },
});

export default strings;
